[package]
name = "osmanthus-guard"
version = "0.1.3"
edition = "2024"
rust-version = "1.91"
license = "MIT"
description = "A lightweight command guard for Linux servers"
repository = "https://github.com/ttr1563/osmanthus-shell"
homepage = "https://ttr1563.github.io/osmanthus-shell/"
readme = "README.md"
keywords = ["security", "cli", "linux", "totp", "audit"]
categories = ["command-line-utilities", "authentication"]
exclude = ["docs/apt/**", "docs/rpm/**", "Formula/**"]

[[bin]]
name = "osmanthus"
path = "src/main.rs"

[[bin]]
name = "osmanthusd"
path = "src/bin/osmanthusd.rs"

[[bin]]
name = "osmanthus-shell"
path = "src/bin/osmanthus-shell.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
data-encoding = "2.9"
hmac = "0.12"
libc = "0.2"
libbpf-rs = "0.27.2"
qrcode = { version = "0.14", default-features = false }
rand = "0.9"
rpassword = "7.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10"
sha2 = "0.10"
thiserror = "2.0"
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }
urlencoding = "2.1"
uuid = { version = "1.18", features = ["v4"] }
zeroize = "1.8"

[build-dependencies]
libbpf-cargo = "0.27.2"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.23"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
